export const state = {
  authenticated: false,
  currentItem: null,
  currentTrackKey: null,
  activeCardKey: null,
  currentGenre: null,
  currentTags: [],
  currentMood: null,
  currentAudioProfile: null,
  nowPlayingPending: false,
  recentPending: false,
  wrappedPending: false,
  activePlaylist: null,
  activeView: "card",
  activeWrappedRange: "short_term",
  activeWrappedPane: "overview",
  activeDayPane: "overview",
  activeRecommendationGroup: 0,
  activePlaylistPane: "genre",
  wrappedReport: null,
  themeMode: "default",
  themeRequestKey: null,
  backdropRequestKey: null,
  currentLyricsLines: [],
  lyricTimeline: [],
  lyricLineElements: [],
  activeLyricLineIndex: -1,
  lyricsInteractive: false,
  lyricsTiming: "plain",
  lyricsFollowEnabled: true,
  lyricsManualUntil: 0,
  lyricsRequestToken: 0,
  visualizerProfile: [],
  lastNowPlayingRequestAt: 0,
  lastRecentRequestAt: 0,
  playRequestToken: 0,
  previousTrackSnapshot: null,
  overviewMode: false,
  roomMode: false,
  roomPreviousView: null,
  overviewPreviousView: null,
  overviewScrollY: 0,
  preferences: {
    reducedMotion: window.matchMedia("(prefers-reduced-motion: reduce)").matches,
    sessionMode: "adaptive",
  },
  playlistOptions: {
    familiarity: 0.58,
    energyBias: 0,
    artistVariety: 0.66,
    explicitMode: "balanced",
  },
};
